[package]
name = "typing-cli"
version = "0.1.0"
edition = "2021"
author = "Random dude"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
crossterm = "0.27.0"
ratatui   =  "0.25.0"
cross = "0.2.5"
